spring.application.name=javauipath
uipath.app-id=${UIPATH_APP_ID}
uipath.app-secret=${UIPATH_APP_SECRET}
uipath.organization=tomaszrpa
uipath.tenant=defaulttenant
uipath.project-id=b9446211-aa89-f111-b337-002248a375c1
uipath.platrofm-url="https://cloud.uipath.com"
